//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;

namespace FeedMeApi
{
    using System;
    using System.Collections.Generic;

    //Conecta al Json y así envía la info
    [Serializable]
    [DataContract]
    public partial class FeedBack
    {
        [DataMember]
        public int FeedBackId { get; set; }
        [DataMember]
        public Nullable<int> StoreId { get; set; }
        [DataMember]
        public Nullable<int> Face { get; set; }
        [DataMember]
        public string Opinion { get; set; }
        [DataMember]
        public Nullable<System.DateTime> CreationDate { get; set; }
        [DataMember]
        public virtual Store Store { get; set; }
    }
}
