//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;

namespace FeedMeApi
{
    using System;
    using System.Collections.Generic;

    [Serializable]
    [DataContract]
    public partial class PeriodType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PeriodType()
        {
            this.Coupons = new HashSet<Coupon>();
            this.Stores = new HashSet<Store>();
        }
        [DataMember]
        public int PeriodId { get; set; }
        [DataMember]
        public string PeriodName { get; set; }
        [DataMember]
        public Nullable<int> Number { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [DataMember]
        public virtual ICollection<Coupon> Coupons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [DataMember]
        public virtual ICollection<Store> Stores { get; set; }
    }
}
