//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;

namespace FeedMeApi
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    [DataContract]
    public class Store
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Store()
        {
            this.Coupons = new HashSet<Coupon>();
            this.FeedBacks = new HashSet<FeedBack>();
            this.Users = new HashSet<User>();
        }
        [DataMember]
        public int StoreId { get; set; }
        [DataMember]
        public string UrlName { get; set; }
        [DataMember]
        public string CodName { get; set; }
        [DataMember]
        public Nullable<int> Discount { get; set; }
        [DataMember]
        public Nullable<int> Amount { get; set; }
        [DataMember]
        public Nullable<double> Percentage { get; set; }
        [DataMember]
        public string ProductDescription { get; set; }
        [DataMember]
        public Nullable<int> PeriodId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Coupon> Coupons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeedBack> FeedBacks { get; set; }
        public virtual PeriodType PeriodType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
    }
}
